[[redirects]]
  from = "/api/*"
  to = "https://api.yelp.com/v3/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200